### ISSUE TITLE
TMC_2208 connections

### ISSUE THREAD

**Issue by vinnyJager** [Sergey-77/Cetus3d_TMC2208#1]
Hi, 

I've got a question about image number 7, double layer pcb. The the stepper drivers connect into the female headers, soldered on to one of the PCB's included in this project. So I'm wondering why is there a cable from the Cetus also connected to the stepper drivers but from above.
And I'm wondering what connectors you use on the pcb's, is there a parts list or something?

Kind regards,
Vincent

**Comment by Sergey-77** [comment]
Index | Quantity | Part Number | Manufacturer Part Number | Description
-- | -- | -- | -- | --
1 | 2 | SAM9312-ND | ESQ-118-14-G-D | CONN SOCKET 36POS 0.1 GOLD PCB
2 | 1 | 3M157849-1-ND | 3365/10 100 | CBL RIBN 10COND 0.050 GRAY 1’
3 | 2 | S9286-ND | SFH210-PPPC-D05-ID-BK | CONN HEADER 10POS IDC 28AWG GOLD
4 | 2 | S9169-ND | SBH11-PBPC-D05-ST-BK | CONN HEADER VERT 10POS 2.54MM

Got connectors from DigiKey. 36 pin connector’s pins were too long. I think SSQ-118-03-G-D would be better choice.

Pins for stepper motor were soldered on top of stepper driver, not on bottom as rest of the pins. Cable from motor connected directly to driver through those pins.
